
language: c

compiler:
  - clang

before_install:
  - git submodule update --init --recursive

# Install cmake
install:
  - sudo apt-get update
  - sudo apt-get -q install cmake valgrind
  - cmake --version
  - clang -v

# Run the Build script
script:
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../_install
  - cmake --build . --target install

